// Root build.gradle delegating to android subproject
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.4'
    }
}

apply from: "android/variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task assembleDebug {
    dependsOn ':android:app:assembleDebug'
}

task assembleRelease {
    dependsOn ':android:app:assembleRelease'
}
